project:
  type: website
  output-dir: docs
  
website:
  title: "Isaac Johnson's Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
